// generated by stringer -type=astOp; DO NOT EDIT

package nm

import "fmt"

const _astOp_name = "opConcatopPredictopStar"

var _astOp_index = [...]uint8{0, 8, 17, 23}

func (i astOp) String() string {
	if i < 0 || i+1 >= astOp(len(_astOp_index)) {
		return fmt.Sprintf("astOp(%d)", i)
	}
	return _astOp_name[_astOp_index[i]:_astOp_index[i+1]]
}
